### ISSUE TITLE
Keeps failing after running for while

### ISSUE THREAD

**Issue by vladkosarev** [freshdesk/hipchat_freshdesk_addon#3]
We set this up on heroku per instructions but every day this plugin fails after working for a while and the only way to get it to work again is to delete and re-add it to hipchat. Restarting heroku doesn't work.

The underlying error seems to be this - 

2015-08-02T20:38:09.649784+00:00 app[web.1]: NoMethodError (undefined method `attributes' for nil:NilClass):
2015-08-02T20:38:09.649786+00:00 app[web.1]:   app/controllers/hipchat_controller.rb:11:in `get_updates'

Thanks.

**Comment by vladkosarev** [comment]
I believe this happens because Heroku is supposed to be read only file system and you write your config to files.

This will now work as described on Heroku.

Switching to Redis to test it out.

**Comment by sathishceg** [comment]
Since we already have a model in place...You can extend it to store data in DB...

**Comment by vladkosarev** [comment]
The point is that as described in your instructions (on heroku) it will not work.
Not everyone is a Ruby developer who will be using this addon. It would be a lot more helpful to users if it worked as described in your step by step instructions.
